Likelion-YeungNam-Univ/ILKAN-was

src/main/java/com/ilkan/controller/UserWorkController.java
src/main/java/com/ilkan/repository/WorkRepository.java
src/main/java/com/ilkan/service/WorkService.java

- #13 
- 자신이 수행중인 일거리 조회를 페이징처리 및 등록시간기준 정렬하였습니다.
- 수행중 필터링은 수행자id와 Status enum의 IN_PROGRESS(진행중) 으로 필터링하였습니다.

[ILKAN-49] feat : 내가 수행중인 작업조회 controller 구현

---

src/main/java/com/ilkan/domain/enums/Role.java

- #13 
- CLIENT -> REQUESTER 로 변경하였습니다.

[ILKAN-49] refactor : Role 역할명 확실히 분리

---

build.gradle
src/main/java/com/ilkan/config/SwaggerConfig.java

- swagger 의존성 추가 및 스프링부트 버전 3.3.2 변경

[ILKAN-107] chore : Swagger 의존성 추가 및 스프링부트 버전 변경

---

src/main/java/com/ilkan/service/AuthService.java

- 전달받은 역할 문자열을 검증하고 Role enum으로 변환
- 대소문자 무시 및 앞뒤 공백 제거 처리

[ILKAN-107] feat : 사용자 인증 기능 - AuthService 추가

---

src/main/java/com/ilkan/auth/AllowedRoles.java

**feat : @AllowedRoles 어노테이션 추가**
- 권한을 허용할 사용자 `Role`을 지정하여 접근을 제한할 수 있도록 함
- 인터셉터에서 해당 어노테이션을 읽은 후 권한 검증

[ILKAN-119] feat : 사용자 인가 기능 - @AllowedRoles 추가

---

src/main/java/com/ilkan/auth/RoleCheckInterceptor.java
src/main/java/com/ilkan/config/WebConfig.java

**1. RoleCheckInterceptor**
- 컨트롤러 진입 전 `@AllowedRoles` 어노테이션 확인
- 요청 헤더값 검증
**2. WebConfig 추가**
- RoleCheckInterceptor를 `/api/** `경로에 적용
- swagger 경로 예외처리

[ILKAN-119] feat : 사용자 인가 기능 - RoleCheckInterceptor 추가 및 WebConfig 등록

---

src/main/java/com/ilkan/domain/entity/Reservation.java
src/main/java/com/ilkan/dto/reservationdto/UserBuildingResDto.java

- Reservation Entity 수행자, 건물주 id 이름 수정

[ILKAN-58] refact : Reservation Entity 이름 수정

---

src/main/java/com/ilkan/domain/entity/Reservation.java
src/main/java/com/ilkan/domain/enums/BuildingStatus.java
src/main/java/com/ilkan/domain/enums/ReservationStatus.java
src/main/java/com/ilkan/dto/reservationdto/UserBuildingResDto.java
src/main/java/com/ilkan/repository/UserBuildingRepository.java
src/main/java/com/ilkan/service/UserBuildingService.java

- 쓸모없는 buildingstatus enum 삭제 후 reservationstatus로 통일

feat : 건물 상태에서 ReservationStatus enum으로 통일

---

.github/workflows/develop.yml
src/main/java/com/ilkan/config/CorsConfig.java
src/main/java/com/ilkan/controller/HealthCheckController.java

이슈 X
- AWS EC2, RDS, Load Balancer를 사용하여 백엔드 서버 배포 및 HTTPS 적용
- CORS 설정을 통한 프론트엔드 서버와 통신 환경 구축
- http 8080으로 요청을 보내도 https으로 리다이렉트
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

배포 및 CORS 설정

---

src/main/java/com/ilkan/controller/UserBuildingController.java
src/main/java/com/ilkan/controller/UserWorkController.java
src/main/java/com/ilkan/service/UserBuildingService.java

- 역할에 따른 검증로직 추가
- 권한이 없다면 403 반환

fix : 컨트롤러에서 역할 검증 로직 추가

---

src/main/java/com/ilkan/controller/UserWorkController.java
src/main/java/com/ilkan/repository/UserBuildingRepository.java
src/main/java/com/ilkan/service/UserBuildingService.java

- BuildingStatus -> ReservationStatus

fix : BuildingStatus -> ReservationStatus

---

src/main/java/com/ilkan/controller/WorksController.java
src/main/java/com/ilkan/domain/entity/User.java
src/main/java/com/ilkan/domain/entity/Work.java
src/main/java/com/ilkan/repository/WorkRepository.java
src/main/java/com/ilkan/service/WorkService.java

ILKAN-122
- 특정 ID를 가진 단일 객체 조회 메서드기 떄문에 페이징 필요X 
- optional 사용으로 인한 taskId 미존재시 null 반환 및 빈 optional 객체 반환
- 이를통해 null 체크 강제화 -> 안전화
- dto 및 entity에 일거리 작업기간 , 모집인원 , 학력 , 우대사항 , 기타조건 , 모집기한 추가

[ILKAN-122] 일거리 상세조회 API

---

src/main/java/com/ilkan/dto/workdto/WorkDetailResDto.java

feat : 일거리 상세조회 dto 구현

---

src/main/java/com/ilkan/controller/UserBuildingController.java
src/main/java/com/ilkan/controller/UserWorkController.java
src/main/java/com/ilkan/controller/WorksController.java
src/main/java/com/ilkan/controller/api/UserBuildingApi.java
src/main/java/com/ilkan/controller/api/UserWorkApi.java
src/main/java/com/ilkan/controller/api/WorksApi.java
src/main/java/com/ilkan/dto/workdto/WorkListResDto.java
src/main/java/com/ilkan/dto/workdto/WorkReqDto.java
src/main/java/com/ilkan/exception/UserBuildingExceptions.java
src/main/java/com/ilkan/exception/UserWorkExceptions.java
src/main/java/com/ilkan/repository/WorkRepository.java
src/main/java/com/ilkan/service/UserBuildingService.java
src/main/java/com/ilkan/service/WorkService.java

- swagger 문서화 및 커스텀 예외처리 진행
- 조회기능 성능최적화를 위해 transactional(readOnly = true) 어노테이션 추가
- 일거리 등록 및 수정 dto 구현
- 일거리 등록 수정 삭제시 권한체크를 위해 레포지토리에 구현

Swagger 문서화 및 커스텀 예외처리

---

src/main/java/com/ilkan/controller/WorksController.java
src/main/java/com/ilkan/domain/entity/User.java
src/main/java/com/ilkan/domain/entity/Work.java
src/main/java/com/ilkan/dto/workdto/WorkDetailResDto.java
src/main/java/com/ilkan/dto/workdto/WorkListResDto.java
src/main/java/com/ilkan/dto/workdto/WorkResDto.java
src/main/java/com/ilkan/dto/workdto/WorkUserResDto.java
src/main/java/com/ilkan/repository/WorkRepository.java
src/main/java/com/ilkan/service/WorkService.java

ILKAN-40
- 일거리 등록/수정/삭제 API 구현
- 불필요 Work 엔티티 필드인 금액합의여부 isNegotiable 삭제

[ILKAN-40] 의뢰자 일거리 등록/수정/삭제 API

---

src/main/java/com/ilkan/dto/workdto/WorkResDto.java
src/main/java/com/ilkan/dto/workdto/WorkUserResDto.java

ILKAN-40
- id -> taskId로 필드명 명확화

fix : task id로 필드명 수정

---

.github/workflows/cd.yml
.github/workflows/ci.yml
Dockerfile

> ILKAN-126
- ci 워크플로우 작성(db 테스트X)
- 도커파일 추가(도커이미지로 배포)
- cd 워크플로우 작성
- 깃허브 시크릿 추가
> 제발 되라

[ILKAN-126] cicd 파이프라인 구축

---

src/main/java/com/ilkan/controller/WorksController.java
src/main/java/com/ilkan/dto/workdto/WorkResDto.java

- 컨트롤러 역할->id 매핑 추가, dto에 모집기한 추가

Fix : 컨트롤러 역할->id 매핑 추가, dto에 모집기한 추가

---

src/main/resources/static/index.html

> ILKAN-127
- cicd 테스트용 pr입니다
- 테스트용 index.html 생성해두었습니다 
> 해치웠나?

[ILKAN-127] cicd 테스트

---

src/main/resources/static/index.html

[ILKAN-128] cicd test2

---

src/main/java/com/ilkan/controller/api/WorksApi.java
src/main/java/com/ilkan/dto/reservationdto/OwnerBuildingResDto.java
src/main/java/com/ilkan/dto/reservationdto/UserBuildingResDto.java
src/main/java/com/ilkan/dto/userdto/UserReqDto.java
src/main/java/com/ilkan/dto/userdto/UserRespDto.java
src/main/java/com/ilkan/dto/workdto/WorkResDto.java

- 기존에 있던 dto swagger 문서화 진행
- works Api sagger 문서화 진행

Docs : dto 및 works Api swagger 문서화

---

.github/workflows/cd.yml
Dockerfile

> ILKAN-130
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

[ILKAN-130] cd 워크 플로우 파일 수정

---

src/main/java/com/ilkan/domain/entity/Building.java
src/main/java/com/ilkan/domain/entity/Work.java
src/main/java/com/ilkan/dto/reservationdto/UserBuildingResDto.java
src/main/java/com/ilkan/dto/userdto/UserReqDto.java
src/main/java/com/ilkan/dto/userdto/UserRespDto.java

feat : 건물명 필드추가

---

src/main/java/com/ilkan/dto/reservationdto/UserBuildingResDto.java

[ILKAN-110] feat : 건물이미지 필드 추가

---

src/main/java/com/ilkan/controller/UserController.java
src/main/java/com/ilkan/controller/api/UserApi.java
src/main/java/com/ilkan/dto/userdto/UserProfileResDto.java
src/main/java/com/ilkan/exception/RoleExceptions.java
src/main/java/com/ilkan/service/UserService.java

**- UserApi 인터페이스 추가 및 스웨거 문서화**
**- UserController 구현 (얇은 컨트롤러)**
`@AllowedRoles({PERFORMER, OWNER, REQUESTER}) `적용 (모든 역할 가능하도록)
**- UserService 프로필 조회 로직 구현**
미존재 시 `UserExceptions.NotFound(role)` 발생

[ILKAN-105] feat : 프로필 조회 API 구현

---

.github/workflows/cd.yml

> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

feat: cd fix

---

src/main/java/com/ilkan/controller/WorksController.java
src/main/java/com/ilkan/controller/api/WorksApi.java
src/main/java/com/ilkan/domain/entity/User.java
src/main/java/com/ilkan/dto/workdto/WorkDetailResDto.java
src/main/java/com/ilkan/dto/workdto/WorkReqDto.java
src/main/java/com/ilkan/repository/WorkRepository.java
src/main/java/com/ilkan/service/WorkService.java

- 일거리 조회 시 카테고리에 대한 필터링 기능필요
- - 이에 따른 필터링 기능 구현
- - 팀원 요청에 따른 일거리 상세조회 모집기한 필드 추가

[ILKAN-Fix] 일거리 등록/조회 카테고리 필터링

---

src/main/java/com/ilkan/controller/BuildingQueryController.java
src/main/java/com/ilkan/controller/api/BuildingQueryApi.java
src/main/java/com/ilkan/domain/entity/Building.java
src/main/java/com/ilkan/domain/enums/BuildingTag.java
src/main/java/com/ilkan/dto/buildingdto/BuildingDetailResDto.java
src/main/java/com/ilkan/exception/BuildingQueryExceptions.java
src/main/java/com/ilkan/service/BuildingQueryService.java

- 공간 상세 조회 API 구현
- 공간 entity 전화번호 추가 + 체크인/체크아웃 필드 타입 변경
- 공간 태그 `getkor()`, `toLabel()` 추가

[ILKAN-101] feat : 공간 상세 조회 API 구현

---

src/main/java/com/ilkan/controller/UserWorkController.java
src/main/java/com/ilkan/controller/api/UserWorkApi.java
src/main/java/com/ilkan/dto/workdto/WorkStatusReqDto.java
src/main/java/com/ilkan/service/WorkService.java

> ILKAN-150
> - ASSIGNED → IN_PROGRESS (의뢰자 '준비완료')
> - IN_PROGRESS → COMPLETED (의뢰자 '보수지급')
> - 위와같이 기능을 구현했고, 이것 두개 이외의 상태로 바꿀시 예외처리 했습니다.
> - 또한, 이것두개 이외의 상태를 가진 일거리가 상태를 변경하려하면 예외처리 했습니다.

[ILKAN-150] 수행자 일거리 준비완료/보수결제 버튼API

---

src/main/java/com/ilkan/controller/BuildingController.java
src/main/java/com/ilkan/controller/api/BuildingCommandApi.java
src/main/java/com/ilkan/exception/BuildingCommandExceptions.java
src/main/java/com/ilkan/repository/ReservationRepository.java
src/main/java/com/ilkan/service/BuildingService.java

- 건물주가 등록한 건물 삭제 구현
- 해당 건물에 예약이 1건이라도 존재 시 삭제 불가능

[ILKAN-78] feat : 건물주가 등록한 건물 삭제 API 구현

---

src/main/java/com/ilkan/domain/building/dto/BuildingDetailResDto.java

- 건물 상세 조회 resDto 수정 -> 건물주 이름, 건물주 사진 추가

[ILKAN-101] feat : 건물 상세 조회 응답 추가 (건물주 이름, 건물주 사진)

---

src/main/java/com/ilkan/domain/work/dto/WorkDetailResDto.java

[ILKAN-95] 일거리 상세조회 모집기한 추가

---

src/main/java/com/ilkan/domain/profile/controller/UserWorkController.java
src/main/java/com/ilkan/domain/profile/dto/performer/WorkResDto.java
src/main/java/com/ilkan/domain/profile/dto/performer/WorkStatusReqDto.java
src/main/java/com/ilkan/domain/profile/dto/requester/WorkUserResDto.java
src/main/java/com/ilkan/domain/work/dto/requester/WorkReqDto.java
src/main/java/com/ilkan/domain/work/entity/Work.java
src/main/java/com/ilkan/domain/work/repository/WorkRepository.java
src/main/java/com/ilkan/domain/work/scheduler/WorkStatusScheduler.java
src/main/java/com/ilkan/domain/work/service/WorkService.java
src/main/java/com/ilkan/domain/work/service/WorkSetStatusService.java

일거리 조회 DTO에 필드 추가
일거리 시작/마감 시간 스케줄러 구현
수행자 프로필 일거리 상태 변경 DTO 필드 추가
일거리 상태 변경 서비스 로직에 작업시간 업데이트 추가
의뢰자 등록 작업 조회 시 모집중, 배정됨 상태만 조회하도록 수정
불필요 필드 제거
일거리 시작/마감 시간 관련 메소드명 변경
DTO 설명 수정

[ILKAN-Fix]

---

src/main/java/com/ilkan/exception/GeminiExceptions.java
src/main/java/com/ilkan/gemini/controller/GeminiController.java
src/main/java/com/ilkan/gemini/dto/GeminiApiResponseDto.java
src/main/java/com/ilkan/gemini/dto/GeminiRequestDto.java
src/main/java/com/ilkan/gemini/dto/GeminiResponseDto.java
src/main/java/com/ilkan/gemini/error/GeminiErrorCode.java
src/main/java/com/ilkan/gemini/service/GeminiService.java
src/main/java/com/ilkan/gemini/service/GeminiServiceImpl.java

feat : 리모델링 AI 구현

---

src/main/java/com/ilkan/domain/work/scheduler/WorkStatusScheduler.java

[ILKAN-Fix] : 스케줄러 실행 기준 UTC로 통일

---

src/main/java/com/ilkan/domain/building/entity/Building.java
src/main/java/com/ilkan/domain/profile/api/UserWorkApi.java
src/main/java/com/ilkan/domain/profile/controller/UserWorkController.java
src/main/java/com/ilkan/domain/work/repository/TaskApplicationRepository.java
src/main/java/com/ilkan/domain/work/service/WorkService.java

feat : 의뢰자 기준 수행자들이 지원한 지원서 목록 조회 수정

---

src/main/java/com/ilkan/domain/work/entity/enums/Status.java

- 수행자 기준 진행 중인 의뢰 상태 추가 (ASSIGNED)

feat : 수행자 기준 진행 중인 의뢰 상태 추가 (ASSIGNED)

---

src/main/java/com/ilkan/domain/work/dto/performer/AlReadyAppliedResDto.java
src/main/java/com/ilkan/domain/work/service/WorkService.java

feat : 중복지원 혹은 지원완료 시 메시지추가

---

src/main/java/com/ilkan/domain/profile/controller/UserBuildingController.java
src/main/java/com/ilkan/domain/profile/controller/UserWorkController.java

[ILKAN-Fix] : 페이징 사이즈 조절

---

src/main/java/com/ilkan/domain/profile/api/UserWorkApi.java
src/main/java/com/ilkan/domain/profile/controller/UserWorkController.java
src/main/java/com/ilkan/domain/work/repository/TaskApplicationRepository.java
src/main/java/com/ilkan/domain/work/service/WorkService.java

fix : 지원자 상세조회 오류해결

---

src/main/java/com/ilkan/domain/building/dto/BuildingCreateReq.java

feat : 건물 초기 상태 설정 수정
